name: tasty_dinery_admin
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# packages

dependencies:
  flutter:
    sdk: flutter

  # utility packages

  smooth_page_indicator: ^1.1.0
  http: ^0.13.5
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  intl: ^0.18.0
  logger: ^2.1.0
  lottie: ^3.0.0
  circular_profile_avatar: ^2.0.5
  awesome_bottom_bar: ^1.2.4
  flutter_native_splash: ^2.3.10
  shimmer: ^3.0.0
  image_picker: ^1.0.4

  # icons

  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.7.0
  flutter_emoji: ^2.5.1
  flutter_spinkit: ^5.2.0

  # state management

  get: ^4.6.5
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

  # product specific

  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  qr: ^3.0.1
  qr_flutter: ^4.1.0
  qr_image: ^1.0.0

  # charts
  syncfusion_flutter_charts: ^25.1.38
  fl_chart: ^0.67.0
  data_table_2: ^2.5.12

  # firebase 
  firebase_core: ^2.27.0
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  firebase_storage: ^11.5.4
  cached_network_image: ^3.3.1
  azampay: ^0.0.1
  pay: ^2.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.1


flutter:


  uses-material-design: true

  # local assets

  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/auth_images/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/mobile_ops/
    - assets/images/products/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/success_screen/
    - assets/lottie_animations/

  # fonts
  
  fonts:
    - family: SanFranciscoPro
      fonts:
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/San-Francisco/San Francisco/pro/SF-Pro-Display-RegularItalic.otf
          style: italic

    


    
